### ISSUE TITLE
SCSS/SASS compilation error during admin startup()

### ISSUE THREAD

**Issue by sebrose** [opencart/opencart#14113]
**What version of OpenCart are you reporting this for?**
OpenCart 3.0.4.0
PHP 8.0 (and 8.4)

**Describe the bug**
My OpenCart 3.0.4.0 install has been working fine with PHP 8.0 for quite a while. I was making some changes to the view and refreshed the theme and SASS cache. The theme refresh worked fine, but the SASS refresh throws an error:

```
Fatal error: Uncaught Error: Call to undefined method ScssPhp\ScssPhp\Compiler::compileString() in /Users/seb/Projects/shop/admin/controller/startup/sass.php:17 
Stack trace: 
#0 /Users/seb/Projects/shop/system/storageundh3m8jmtxd/modification/system/engine/action.php(79): ControllerStartupSass->index() 
#1 /Users/seb/Projects/shop/system/engine/router.php(67): Action->execute(Object(Registry)) 
#2 /Users/seb/Projects/shop/system/engine/router.php(46): Router->execute(Object(Action)) 
#3 /Users/seb/Projects/shop/system/framework.php(179): Router->dispatch(Object(Action), Object(Action)) 
#4 /Users/seb/Projects/shop/system/startup.php(104): require_once('/Users/seb/Proj...') 
#5 /Users/seb/Projects/shop/admin/index.php(19): start('admin') 
#6 {main} thrown in /Users/seb/Projects/shop/admin/controller/startup/sass.php on line 17

```

This error is preventing me from accessing the OpenCart admin dashboard.

**To Reproduce**
I am unable to describe how to cause this error from a clean install. I have several extension installed that I purchased from the OC marketplace, but I couldn't say which 

**Expected behavior**
I expect to be able to access the admin dashboard without errors.

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? Both.
 - Operating system: MacOS (local)
 - PHP version: 8.0 and 8.4
 - Apache version: 2.4.62 (local)
 - Version [e.g. 22] : of what?

**Additional context**
OC extensions:
<img width="495" alt="image" src="https://github.com/user-attachments/assets/9fbdba63-85e4-4bd6-b7dd-3b90078a7e3f">

I tried posting this on the OC community forum, but was blocked by Cloudflare

**Comment by mhcwebdesign** [comment]
It looks like you are using an older version of the scss vendor library, maybe you did an upgrade instead of a fresh install.

Please delete and then restore from the 3.0.4.0 the system/storage/vendor/scssphp folder with all its files from the https://github.com/opencart/opencart/tree/3.0.4.0/upload/system/storage/vendor/scssphp

**Comment by sebrose** [comment]
The version of scssphp in my install is 1.12.1 - which looks identical to the one shipping with OC 3.0.4.0

I copied the 3.0.4.0 scssphp folder tree over, just in case, but the same problem happens.

FWIW I restarted httpd, php, and mysql ...

**Comment by sebrose** [comment]
Yes:

**Comment by mhcwebdesign** [comment]
I am simply unable to reproduce your error. Try a genuinely fresh install of OC 3.0.4.0 on your MacOS computer, without any extensions, to find out whether the error was caused by any extension, or an upgrade from an older version.

**Comment by sebrose** [comment]
Will do. Thanks for your help.
