### ISSUE TITLE
vsprintf(): Too few arguments Warning

### ISSUE THREAD

**Issue by anilex** [opencart/opencart#4149]
After upgrade from 2.0.3.2 to 2.1.0.2 and login to admin area I got this error: 

`Warning: vsprintf(): Too few arguments in /home/website_name/public_html/admin/controller/dashboard/activity.php on line 19`

for the line 19: 
`$comment = vsprintf( $this->language->get('text_' . $result['key']) , json_decode($result['data'], true));`

where the second argument is NULL

**Comment by danielkerr** [comment]
clear the activity log
